services:

  server:
    image: node:20
    volumes:
      - ./server:/code
    working_dir: /code
    ports:
      - ${HOST_PORT_SERVER}:8888
    entrypoint:
      - /bin/bash
      - -c
      - |
        npm i
        npm start