services:

  server:
    image: node:20
    volumes:
      - ./server:/code
    working_dir: /code
    ports:
      - ${HOST_PORT_SERVER}:8888
    environment:
      PAYPAL_CLIENT_ID:
      PAYPAL_CLIENT_SECRET:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    entrypoint:
      - /bin/bash
      - -c
      - |
        npm i
        npm start

  client:
    image: node:20
    volumes:
      - ./client:/code
    working_dir: /code
    ports:
      - ${HOST_PORT_CLIENT}:3000
    environment:
      VITE_API_BASE_URL: http://localhost:${HOST_PORT_SERVER}
      VITE_PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
    depends_on:
      server:
        condition: service_healthy
    entrypoint:
      - /bin/bash
      - -c
      - |
        yarn
        yarn dev